export const starterLayoutContent = {
  brand: 'Artist Name / Logo',
  hero: {
    headline: 'Primary Homepage Headline',
    introduction: 'Introductory Text',
    primaryAction: 'Primary Action',
    secondaryAction: 'Secondary Action',
  },
  featuredRelease: {
    metadata: 'Release Metadata',
    title: 'Featured Release / Artwork',
    format: 'Release Format / Description',
    artist: 'Artist Name',
  },
  trackDetail: {
    title: 'Track Title',
    description: 'Track Description',
    detailsLabel: 'Track Details',
    detailsHeading: 'Track Metadata',
    libraryLabel: 'Listener Library',
    libraryHeading: 'Favorites and Playlists',
    returnAction: 'Return to Album',
  },
  releaseDetail: {
    title: 'Album Title',
    description: 'Album Description',
    trackTitle: 'Track Title',
    playAction: 'Play Preview',
    previewStatus: 'Preview Processing Status',
    playbackStatus: 'Preview Playback Status',
    creditsLabel: 'Release Credits',
    creditsHeading: 'Release Credit List',
    creditRole: 'Credit Role',
    creditName: 'Credit Name',
    note: 'Release Note',
  },
  collectionDetail: {
    title: 'Collection Title',
    description: 'Collection Description',
  },
  about: {
    title: 'Artist Name',
    introduction: 'Artist Biography',
    locationLabel: 'Artist Location Label',
    location: 'Artist Location',
    factLabel: 'Artist Fact Label',
    fact: 'Artist Fact',
  },
  contact: {
    title: 'Contact Page Heading',
    introduction: 'Contact Page Introduction',
    consent: 'Contact Form Consent Text',
    bookingNote: 'Contact Details / Booking Note',
    email: 'Public Contact Email',
    address: 'Public Mailing Address',
    localNote: 'Local Contact Form Delivery Note',
  },
  support: {
    title: 'Support Page Heading',
    introduction: 'Support Page Introduction',
    offeringTitle: 'Offering Title',
    offeringDescription: 'Offering Description',
    offeringPrice: 'Offering Price',
    offeringAction: 'Offering Action',
    externalAction: 'External Offering Action',
    localNote: 'Local Payment Provider Note',
  },
  licensing: {
    title: 'Licensing Page Heading',
    introduction: 'Licensing Page Introduction',
    trackTitle: 'Track Title',
    templateTitle: 'License Template Title',
    templateSummary: 'License Template Summary',
    templateIntroduction: 'License Template Introduction',
    category: 'Usage Category',
    optionTitle: 'License Option Title',
    optionDescription: 'License Option Description',
    price: 'License Price',
    termValue: 'License Term Value',
    checkoutAction: 'License Checkout Action',
    generalTerms: 'General Terms and Document Notice',
    termHeading: 'General Term Heading',
    termBody: 'General Term Text',
    disclaimer: 'License Document Disclaimer',
    inquiryLabel: 'Custom License Section Label',
    inquiryTitle: 'Custom License Inquiry Heading',
    inquiryText: 'Custom License Inquiry Text',
    inquiryAction: 'Custom License Inquiry Action',
  },
  learning: {
    title: 'Learning Page Heading',
    introduction: 'Learning Page Introduction',
    area: 'Learning Area',
    pathTitle: 'Learning Path Title',
    pathSummary: 'Learning Path Summary',
    pathIntroduction: 'Learning Path Introduction',
    pathAction: 'Open Learning Path',
    nextAction: 'Next Lesson Action',
    courseLabel: 'Course Number',
    courseTitle: 'Course Title',
    courseSummary: 'Course Summary',
    lessonTitle: 'Lesson Title',
    lessonSummary: 'Lesson Summary',
    lessonDuration: 'Duration',
    lessonAccess: 'Access Type',
    lessonAccessExplanation: 'Lesson Access Explanation',
    lessonAction: 'Open Lesson',
    sectionLabel: 'Lesson Section Label',
    sectionHeading: 'Lesson Section Heading',
    sectionBody: 'Lesson Section Text',
    imageAlt: 'Lesson Image Placeholder',
    imageCaption: 'Lesson Image Caption',
    audioPrompt: 'Lesson Audio Prompt',
    audioTranscript: 'Lesson Audio Transcript',
    downloadDescription: 'Lesson Download Description',
    downloadAction: 'Lesson Download Action',
    practiceLabel: 'Practice Section Label',
    practiceText: 'Practice Prompt Text',
    completionLabel: 'Lesson Completion Label',
    completionHeading: 'Lesson Completion Heading',
    completionText: 'Lesson Completion Instructions',
    previousAction: 'Previous Lesson',
    nextLessonAction: 'Next Lesson',
  },
  video: {
    title: 'Video Page Heading',
    introduction: 'Video Page Introduction',
    provider: 'Video Provider',
    itemTitle: 'Video Title',
    itemSummary: 'Video Description',
    openAction: 'Open Video and Transcript',
    providerNotice: 'External Video Provider Notice',
    transcript: 'Video Transcript',
    creditRole: 'Video Credit Role',
    creditName: 'Video Credit Name',
  },
  journal: {
    title: 'Journal Page Heading',
    introduction: 'Journal Page Introduction',
    metadata: 'Entry Type / Publication Date',
    itemTitle: 'Journal Entry Title',
    itemSummary: 'Journal Entry Summary',
    openAction: 'Open Journal Entry',
  },
  account: {
    title: 'Account Page Heading',
    introduction: 'Account Page Introduction',
    purchasesHeading: 'Order History',
    membershipHeading: 'Membership Status',
    licensesHeading: 'Issued Licenses',
    accessHeading: 'Account Access Ledger',
    learningHeading: 'Learning Progress',
    favoritesHeading: 'Favorite Tracks',
    playlistsHeading: 'Listener Playlists',
    historyHeading: 'Listening History',
  },
  auth: {
    signInTitle: 'Sign-In Page Heading',
    signInIntroduction: 'Sign-In Page Introduction',
    signUpTitle: 'Sign-Up Page Heading',
    signUpIntroduction: 'Sign-Up Page Introduction',
  },
  privacy: {
    title: 'Privacy Page Heading',
    introduction: 'Privacy Page Introduction',
    collectionHeading: 'Optional Analytics Details',
    controlHeading: 'Privacy Preference Controls',
    retentionHeading: 'Data Retention and Operations',
  },
  checkout: {
    simulationTitle: 'Offering Title',
  },
  structuredSection: {
    label: 'Section Label / Number',
    heading: 'Section Heading',
    body: 'Section Body',
    imageAlt: 'Page Image Placeholder',
    imageCaption: 'Image Caption',
    action: 'Section Action',
    creditRole: 'Credit Role',
    creditName: 'Credit Name',
    link: 'External Link Label',
    featuredReleaseLabel: 'Featured Release',
    featuredReleaseHeading: 'Featured Release Heading',
    featuredReleaseAction: 'Open Featured Release',
    featuredLearningLabel: 'Featured Learning',
    featuredLearningHeading: 'Featured Learning Heading',
    featuredLearningAction: 'Open Featured Learning',
    videoHeading: 'Embedded Video Heading',
    videoTranscript: 'Embedded Video Transcript',
  },
  supportingSection: {
    label: 'Section Label / Number',
    headline: 'Supporting Section Headline',
    introduction: 'Supporting Section Text',
    items: Array.from({ length: 3 }, () => ({
      label: 'List Item Heading',
      text: 'List Item Description',
    })),
  },
  closingSection: {
    label: 'Section Label / Number',
    headline: 'Secondary Section Headline',
    text: 'Supporting Text',
  },
  footer: {
    artist: 'Footer Artist Name',
    statement: 'Footer Statement',
    metadata: 'Footer Metadata',
  },
  seo: {
    title: 'Artist-Owned Site Starter',
    description: 'A guided first-clone layout that labels each artist-editable site element.',
  },
} as const
